### ISSUE TITLE
Issues with PWA

### ISSUE THREAD

**Issue by kaknut** [anges244/evie#1]
Evie is failing to register a service worker. Seems to be an issue.

Also '#' needs to be removed from main javascript.
https://www.chromestatus.com/feature/5656049583390720

**Comment by anges244** [comment]
Hi, can you please expand a bit on each case? Are you using the production or development version? Please provide examples of the issues that occured.

**Comment by kaknut** [comment]
Hey,
I tried the production one.

Tried to register service worker using by adding this to the js file:

if (navigator.serviceWorker.controller) {
  console.log('active service worker found, no need to register')
} else {
  //Register the ServiceWorker
  navigator.serviceWorker.register('/service-worker.js', {
    scope: './'
  }).then(function(reg) {
    console.log('Service worker has been registered for scope:'+ reg.scope);
  });
}

Registration was failing whereas this works fine with other themes.

**Comment by anges244** [comment]
Hi and sorry for the delayed response. When I try your code on Chrome and Firefox it works... Can't seem to replicate the problem. Where exactly do you add that? Try outside the event listener

**Comment by kaknut** [comment]
![abc](https://user-images.githubusercontent.com/33004850/46245451-6ef47900-c40b-11e8-824d-0cd08da5e187.PNG)
